# Feriados según la librería `holidays`

Este notebook genera un DataFrame con los feriados oficiales de Chile y Perú, junto con la descripción asociada a cada uno, usando la librería `holidays`.

In [1]:
import pandas as pd
import holidays

# Definir año a analizar (puedes cambiarlo libremente)
anio = 2026

# Crear objeto de feriados para Chile
feriados_cl = holidays.CL(years=[anio])

# Convertir a DataFrame
df_feriados = pd.DataFrame([
    {'FECHA': fecha, 'FERIADO': nombre}
    for fecha, nombre in feriados_cl.items()
])

# Ordenar por fecha
df_feriados['FECHA'] = pd.to_datetime(df_feriados['FECHA'])
df_feriados = df_feriados.sort_values('FECHA').reset_index(drop=True)

df_feriados

        FECHA                                            FERIADO
0  2026-01-01                                          Año Nuevo
1  2026-04-03                                      Viernes Santo
2  2026-04-04                                       Sábado Santo
3  2026-05-01                           Día Nacional del Trabajo
4  2026-05-21                         Día de las Glorias Navales
5  2026-06-21              Día Nacional de los Pueblos Indígenas
6  2026-06-29                              San Pedro y San Pablo
7  2026-07-16                                  Virgen del Carmen
8  2026-08-15                              Asunción de la Virgen
9  2026-09-18                            Día de la Independencia
10 2026-09-19                    Día de las Glorias del Ejército
11 2026-10-12                    Día del Encuentro de dos Mundos
12 2026-10-31  Día Nacional de las Iglesias Evangélicas y Pro...
13 2026-11-01                            Día de Todos los Santos
14 2026-12-08                           La Inmaculada Concepción
15 2026-12-25                                            Navidad

## Notas
- La columna **FERIADO** corresponde exactamente al nombre entregado por la librería `holidays`.
- Si un feriado cambia de fecha por ley o decreto, la librería lo ajusta automáticamente.
- Puedes usar este DataFrame directamente para cruces con ventas o clasificación de días.

In [2]:
feriados_pe = holidays.PE(years=[anio])

df_feriados_pe = pd.DataFrame([
    {'FECHA': fecha, 'FERIADO': nombre}
    for fecha, nombre in feriados_pe.items()
])

df_feriados_pe['FECHA'] = pd.to_datetime(df_feriados_pe['FECHA'])
df_feriados_pe = df_feriados_pe.sort_values('FECHA').reset_index(drop = True)

df_feriados_pe

        FECHA                        FERIADO
0  2026-01-01                      Año Nuevo
1  2026-04-02                   Jueves Santo
2  2026-04-03                  Viernes Santo
3  2026-04-05        Domingo de Resurrección
4  2026-05-01                Día del Trabajo
5  2026-06-29          San Pedro y San Pablo
6  2026-07-28        Día de la Independencia
7  2026-07-29  Día de la Gran Parada Militar
8  2026-08-06               Batalla de Junín
9  2026-08-30             Santa Rosa de Lima
10 2026-10-08             Combate de Angamos
11 2026-11-01               Todos Los Santos
12 2026-12-08          Inmaculada Concepción
13 2026-12-09            Batalla de Ayacucho
14 2026-12-25              Navidad del Señor